### PR TITLE
Eliminate byte conversations

### PR DESCRIPTION
**Pull request by adamradocz**
Make the byte typed search values as constants.

### CODE REVIEW

**Comment by buybackoff** [comment]
I would be surprised if .NET does not do this for us

**Comment by adamradocz** [comment]
> I would be surprised if .NET does not do this for us

Measure it with benchmark.net ;)

**Comment by nietras** [comment]
Won't make a perf difference, but defining as consts is good practice no matter what, but I'd recommend following dotnet naming guidelines. Pascal case. LineFeedByte, CarriageReturnByte. \n is line feed, there is no new line character. CRLF.

**Comment by adamradocz** [comment]
> Won't make a perf difference, but defining as consts is good practice no matter what, but I'd recommend following dotnet naming guidelines. Pascal case. LineFeedByte, CarriageReturnByte. \n is line feed, there is no new line character. CRLF.

**Comment by buybackoff** [comment]
They are constants. And when I see `';'` I know it's a semicolon, I do not need a long name.

Using constants is good when they could change and used multiple times. Here it's a single use for each.

image

**Comment by nietras** [comment]
> They are constants.

Absolutely, didn't mean to say otherwise. It can help people navigate/read code base, find where this is, is used and so on even if only one place, that's all. But no problem.

**Pull request closed without merging**
